name: fastai
channels:
  - pytorch
  - conda-forge
  - fastchan
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - aiohttp=3.7.4.post0=py39h7f8727e_2
  - anyio=3.3.2=py39hf3d152e_0
  - argon2-cffi=20.1.0=py39h3811e60_2
  - async-timeout=3.0.1=py39h06a4308_0
  - async_generator=1.10=py_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - babel=2.9.1=pyh44b312d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - black=21.12b0=pyhd8ed1ab_0
  - blackcellmagic=0.0.2=pyh9f0ad1d_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd8ed1ab_0
  - boto3=1.18.21=pyhd3eb1b0_0
  - botocore=1.21.41=pyhd3eb1b0_1
  - bottleneck=1.3.2=py39hdd57654_1
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py39h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.2.1=h06a4308_0
  - cachetools=4.2.2=pyhd3eb1b0_0
  - catalogue=2.0.6=py39hf3d152e_0
  - certifi=2021.10.8=py39h06a4308_2
  - cffi=1.14.6=py39h400218f_0
  - chardet=4.0.0=py39h06a4308_1003
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - click=8.0.1=pyhd3eb1b0_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - coverage=5.5=py39h27cfd23_2
  - cryptography=3.4.8=py39hd23ed53_0
  - cudatoolkit=11.1.1=h6406543_9
  - cycler=0.10.0=py39h06a4308_0
  - cymem=2.0.5=py39h2531618_0
  - cython=0.29.24=py39h295c915_0
  - cython-blis=0.7.4=py39h27cfd23_1
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.4.1=py39he80948d_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd8ed1ab_0
  - entrypoints=0.3=py39hde42818_1002
  - expat=2.4.1=h2531618_2
  - fastai=2.5.2=py_0
  - fastcore=1.3.26=py_0
  - fastdownload=0.0.5=py_0
  - fastprogress=1.0.0=pyh39e3cac_0
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.13.1=h6c09931_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.10.4=h5ab3b9f_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h5202010_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - google-api-core=1.25.1=pyhd3eb1b0_0
  - google-auth=1.33.0=pyhd3eb1b0_0
  - google-cloud-core=1.7.1=pyhd3eb1b0_0
  - google-cloud-storage=1.31.0=py_0
  - google-crc32c=1.1.2=py39h27cfd23_0
  - google-resumable-media=1.3.1=pyhd3eb1b0_1
  - googleapis-common-protos=1.53.0=py39h06a4308_0
  - grpcio=1.36.1=py39h2157cd5_1
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - idna=3.2=pyhd3eb1b0_0
  - importlib-metadata=4.8.1=py39h06a4308_0
  - intel-openmp=2021.3.0=h06a4308_3350
  - ipykernel=6.4.1=py39hef51801_0
  - ipython=7.28.0=py39hef51801_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.18.0=py39hf3d152e_2
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jmespath=0.10.0=pyhd3eb1b0_0
  - joblib=1.0.1=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=4.0.1=pyhd8ed1ab_0
  - jupyter_client=6.1.12=pyhd8ed1ab_0
  - jupyter_core=4.8.1=py39hf3d152e_0
  - jupyter_server=1.11.1=pyhd8ed1ab_0
  - jupyterlab=3.1.17=pyhd8ed1ab_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=2.8.2=pyhd8ed1ab_0
  - jupyterlab_widgets=1.1.0=pyhd8ed1ab_0
  - kiwisolver=1.3.1=py39h2531618_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcrc32c=1.1.1=he6710b0_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1d223b6_9
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libiconv=1.16=h516909a_0
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.16.0=h780b84a_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=11.2.0=he4da1e4_9
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.0.1=py39h27cfd23_0
  - matplotlib=3.4.2=py39h06a4308_0
  - matplotlib-base=3.4.2=py39hab158f2_0
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mistune=0.8.4=py39h3811e60_1004
  - mkl=2021.3.0=h06a4308_520
  - mkl-service=2.4.0=py39h7f8727e_0
  - mkl_fft=1.3.0=py39h42c9631_2
  - mkl_random=1.2.2=py39h51133e4_0
  - multidict=5.1.0=py39h27cfd23_2
  - munkres=1.1.4=py_0
  - murmurhash=1.0.5=py39h2531618_0
  - mypy_extensions=0.4.3=py39hf3d152e_4
  - nbclassic=0.3.2=pyhd8ed1ab_0
  - nbclient=0.5.4=pyhd8ed1ab_0
  - nbformat=5.1.3=pyhd8ed1ab_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.5.1=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=hff7bd54_1
  - notebook=6.4.4=pyha770c72_0
  - numexpr=2.7.3=py39h22e1b3c_1
  - numpy=1.20.3=py39hf144106_0
  - numpy-base=1.20.3=py39h74d4b33_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1n=h7f8727e_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.3=py39h8c16a72_0
  - pandoc=2.14.2=h7f98852_0
  - pandocfilters=1.5.0=pyhd8ed1ab_0
  - parso=0.8.2=pyhd8ed1ab_0
  - pathspec=0.9.0=pyhd8ed1ab_0
  - pathy=0.6.0=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py39hde42818_1002
  - pillow=8.3.1=py39h5aabda8_0
  - pip=21.2.4=py37h06a4308_0
  - platformdirs=2.3.0=pyhd8ed1ab_0
  - preshed=3.0.5=py39h2531618_4
  - prometheus_client=0.11.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.20=pyha770c72_0
  - protobuf=3.16.0=py39he80948d_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pyasn1=0.4.8=pyhd3eb1b0_0
  - pyasn1-modules=0.2.8=py_0
  - pycparser=2.20=py_2
  - pydantic=1.8.2=py39h27cfd23_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39h2531618_6
  - pyrsistent=0.17.3=py39h3811e60_2
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.9.1=py3.9_cuda11.1_cudnn8.0.5_0
  - pytz=2021.1=pyhd3eb1b0_0
  - pyyaml=5.4.1=py39h27cfd23_1
  - pyzmq=22.3.0=py39h37b5a0c_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.1=h27cfd23_0
  - requests=2.26.0=pyhd3eb1b0_0
  - requests-unixsocket=0.2.0=py_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - s3transfer=0.5.0=pyhd3eb1b0_0
  - scikit-learn=0.24.2=py39ha9443f7_0
  - scipy=1.7.1=py39h292c36d_2
  - send2trash=1.8.0=pyhd8ed1ab_0
  - setuptools=58.0.4=py39h06a4308_0
  - shellingham=1.3.1=pyhd3eb1b0_0
  - sip=4.19.13=py39h2531618_0
  - six=1.16.0=pyhd3eb1b0_0
  - smart_open=5.1.0=pyhd3eb1b0_0
  - sniffio=1.2.0=py39hf3d152e_1
  - spacy=3.1.3=py39h5472131_0
  - spacy-legacy=3.0.8=pyhd8ed1ab_0
  - sqlite=3.36.0=hc218d9a_0
  - srsly=2.4.1=py39h2531618_0
  - terminado=0.12.1=py39hf3d152e_0
  - testpath=0.5.0=pyhd8ed1ab_0
  - thinc=8.0.10=py39h5472131_1
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_0
  - tomli=1.2.2=pyhd8ed1ab_0
  - torchtext=0.10.1=py39
  - torchvision=0.10.1=py39_cu111
  - tornado=6.1=py39h27cfd23_0
  - tqdm=4.62.2=pyhd3eb1b0_1
  - traitlets=5.1.0=pyhd8ed1ab_0
  - typed-ast=1.5.1=py39h3811e60_0
  - typer=0.4.0=pyhd8ed1ab_0
  - typing-extensions=3.10.0.2=hd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - tzdata=2021a=h5d7bf9c_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - voila=0.2.16=pyhd8ed1ab_0
  - voila-gridstack=0.2.0=pyhd8ed1ab_0
  - wasabi=0.8.2=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - websocket-client=0.57.0=py39hf3d152e_4
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.6.3=py39h27cfd23_0
  - zeromq=4.3.4=h9c3ff4c_1
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - fastbook==0.0.18
    - fastrelease==0.1.12
    - ghapi==0.1.19
    - ipywidgets==7.6.5
    - jupyter==1.0.0
    - jupyter-console==6.4.0
    - jupyterlab-widgets==1.0.2
    - msgpack==1.0.3
    - nbconvert==5.6.1
    - nbdev==1.1.22
    - python-graphviz==0.17
    - qtconsole==5.1.1
    - qtpy==1.11.2
    - sentencepiece==0.1.96
    - widgetsnbextension==3.5.1
